import { z } from 'zod';

/**
 * Codes d'erreur stables renvoyés par l'API. Les clients traduisent le code ;
 * l'API ne renvoie jamais de message destiné à être affiché tel quel.
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  CSRF_REJECTED: 'CSRF_REJECTED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  HOUSEHOLD_NOT_FOUND: 'HOUSEHOLD_NOT_FOUND',
  INVITATION_INVALID: 'INVITATION_INVALID',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  GOOGLE_NOT_CONFIGURED: 'GOOGLE_NOT_CONFIGURED',
  GOOGLE_FAILED: 'GOOGLE_FAILED',
  GOOGLE_EMAIL_EXISTS: 'GOOGLE_EMAIL_EXISTS',
  GOOGLE_ALREADY_LINKED: 'GOOGLE_ALREADY_LINKED',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  CONFIRMATION_REQUIRED: 'CONFIRMATION_REQUIRED',
  CALENDAR_NOT_CONFIGURED: 'CALENDAR_NOT_CONFIGURED',
  CALENDAR_NOT_CONNECTED: 'CALENDAR_NOT_CONNECTED',
  CALENDAR_READ_ONLY: 'CALENDAR_READ_ONLY',
  CALENDAR_NOT_FOUND: 'CALENDAR_NOT_FOUND',
  GOOGLE_REVOKED: 'GOOGLE_REVOKED',
  GOOGLE_FLOW_EXPIRED: 'GOOGLE_FLOW_EXPIRED',
  GOOGLE_DENIED: 'GOOGLE_DENIED',
  GOOGLE_SCOPES_MISSING: 'GOOGLE_SCOPES_MISSING',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  IDEMPOTENCY_KEY_INVALID: 'IDEMPOTENCY_KEY_INVALID',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
  CATEGORY_NAME_TAKEN: 'CATEGORY_NAME_TAKEN',
  TASK_TITLE_REQUIRED: 'TASK_TITLE_REQUIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  PASSKEY_FAILED: 'PASSKEY_FAILED',
  ATTACHMENT_TOO_LARGE: 'ATTACHMENT_TOO_LARGE',
  ATTACHMENTS_QUOTA: 'ATTACHMENTS_QUOTA',
  RECEIPT_SCAN_UNAVAILABLE: 'RECEIPT_SCAN_UNAVAILABLE',
  INTERNAL: 'INTERNAL',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    /** Message technique en anglais, pour les logs/développeurs uniquement. */
    message: string;
    details?: unknown;
  };
}

/** Erreur survenue dans le navigateur ou l'app Android, remontée à l'API (logs + Sentry). */
export const ClientErrorInput = z.object({
  source: z.enum(['web', 'android']),
  message: z.string().trim().min(1).max(500),
  stack: z.string().max(8000).optional(),
  /** Chemin de la page (sans paramètres) ou écran Android. */
  location: z.string().max(200).optional(),
  release: z.string().max(40).optional(),
});
export type ClientErrorInput = z.infer<typeof ClientErrorInput>;
